#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# These are the doc steps. They are factored out, but merely depend on
# one single build.

build docs:
    image: stellargroup/build_env:ubuntu
    stage: build
    script:
        - cd build
        - ninja docs
    except:
        - gh-pages
    artifacts:
        when: on_success
        paths:
            - build
    dependencies:
        - checkout
        - cmake Debug x86
    tags:
        - linux
        - x86
        - clang-7.0.1
        - boost-1.65.1
